-- MySQL Script generated by MySQL Workbench
-- Thu Aug  1 21:11:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SEMESTRE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SEMESTRE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SEMESTRE` (
  `Id_Semestre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Semestre`),
  UNIQUE INDEX `Id_Semestre_UNIQUE` (`Id_Semestre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MATERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MATERIA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MATERIA` (
  `Id_Materia` VARCHAR(20) NOT NULL,
  `Nombre_Materia` VARCHAR(45) NULL,
  `Creditos` INT NULL,
  `Descripcion` VARCHAR(405) NULL,
  `SEMESTRE_Id_Semestre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Materia`),
  INDEX `fk_MATERIA_SEMESTRE_idx` (`SEMESTRE_Id_Semestre` ASC) VISIBLE,
  CONSTRAINT `fk_MATERIA_SEMESTRE`
    FOREIGN KEY (`SEMESTRE_Id_Semestre`)
    REFERENCES `mydb`.`SEMESTRE` (`Id_Semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACTIVIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ACTIVIDAD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ACTIVIDAD` (
  `Id_Actividad` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Actividad` VARCHAR(100) NULL,
  `Porcentaje` INT NULL,
  `Calificacion` DECIMAL(2) NULL,
  `Descripcion` VARCHAR(450) NULL,
  PRIMARY KEY (`Id_Actividad`),
  UNIQUE INDEX `Id_Actividad_UNIQUE` (`Id_Actividad` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONFIGURACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CONFIGURACION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CONFIGURACION` (
  `Id_Configuracion` INT NOT NULL,
  `Calificacion_Minima` DECIMAL(2) NULL,
  `Calificacion_Maxima` DECIMAL(2) NULL,
  `Calificacion_Aprobado` DECIMAL(2) NULL,
  PRIMARY KEY (`Id_Configuracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MATERIA_has_ACTIVIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MATERIA_has_ACTIVIDAD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MATERIA_has_ACTIVIDAD` (
  `MATERIA_Id_Materia` VARCHAR(20) NOT NULL,
  `ACTIVIDAD_Id_Actividad` INT NOT NULL,
  PRIMARY KEY (`MATERIA_Id_Materia`, `ACTIVIDAD_Id_Actividad`),
  INDEX `fk_MATERIA_has_ACTIVIDAD_ACTIVIDAD1_idx` (`ACTIVIDAD_Id_Actividad` ASC) VISIBLE,
  INDEX `fk_MATERIA_has_ACTIVIDAD_MATERIA1_idx` (`MATERIA_Id_Materia` ASC) VISIBLE,
  CONSTRAINT `fk_MATERIA_has_ACTIVIDAD_MATERIA1`
    FOREIGN KEY (`MATERIA_Id_Materia`)
    REFERENCES `mydb`.`MATERIA` (`Id_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATERIA_has_ACTIVIDAD_ACTIVIDAD1`
    FOREIGN KEY (`ACTIVIDAD_Id_Actividad`)
    REFERENCES `mydb`.`ACTIVIDAD` (`Id_Actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
